name: Setup October CMS
description: Installs October CMS and dependencies for testing plugins
inputs:
  plugin:
    description: "The plugin directory to store the current plugin repository within, eg: 'author/plugin'"
    required: true
  cmsVersion:
    description: The October CMS version to install
    required: true
    default: dev-develop as 1.1
  libraryVersion:
    description: The Rain Library version to install
    required: true
    default: dev-develop as 1.1
runs:
  using: composite
  steps:
    - name: Stage plugin
      shell: bash
      run: |
        cd ${{ github.workspace }}
        mkdir -p staged-plugin
        shopt -s extglob dotglob nullglob
        mv * staged-plugin/
    - name: Define October CMS and dependencies
      shell: bash
      run: |
        composer create-project --no-install --ignore-platform-reqs  october/october october
        composer require --fixed --no-update october/system -q "${{ inputs.cmsVersion }}"
        composer require --fixed --no-update october/backend -q "${{ inputs.cmsVersion }}"
        composer require --fixed --no-update october/cms -q "${{ inputs.cmsVersion }}"
        composer require --fixed --no-update october/library -q "${{ inputs.libraryVersion }}"
    - name: Move plugin and October CMS into place
      shell: bash
      run: |
        shopt -s dotglob nullglob
        mv ${{ github.workspace }}/plugin/* ${{ github.workspace }}/october/plugins/
        mv ${{ github.workspace }}/october/* ${{ github.workspace }}
        rmdir ${{ github.workspace }}/plugin
        rmdir ${{ github.workspace }}/october
    - name: Install October CMS
      shell: bash
      run: composer update --ignore-platform-reqs --no-progress
