name: Setup October CMS
description: Installs October CMS and dependencies for testing plugins

inputs:
  plugin:
    description: "The plugin directory to store the current plugin repository within, eg: 'author/plugin'"
    required: true
  cmsVersion:
    description: The October CMS version to install
    required: true
    default: dev-develop as 1.1

runs:
  using: composite
  steps:
    - name: Stage plugin
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/plugin/${{ inputs.plugin }}
        ls -1A ${{ github.workspace }} | grep -v ^plugin$ | xargs -I{} mv {} ${{ github.workspace }}/plugin/${{ inputs.plugin }}
        
    - name: Prepare October CMS and dependencies
      shell: bash
      run: |
        composer create-project --ignore-platform-reqs --no-install --no-progress --no-scripts october/october ${{ github.workspace }}/october "${{ inputs.cmsVersion }}"
        composer require --working-dir="${{ github.workspace }}/october" --fixed --no-update --no-scripts october/system "${{ inputs.cmsVersion }}"
        composer require --working-dir="${{ github.workspace }}/october" --fixed --no-update --no-scripts october/backend "${{ inputs.cmsVersion }}"
        composer require --working-dir="${{ github.workspace }}/october" --fixed --no-update --no-scripts october/cms "${{ inputs.cmsVersion }}"
        composer require --working-dir="${{ github.workspace }}/october" --fixed --no-update --no-scripts october/rain "${{ inputs.cmsVersion }}"
        
    - name: Move plugin into location
      shell: bash
      run: |
        mv ${{ github.workspace }}/plugin/* ${{ github.workspace }}/october/plugins
        shopt -s dotglob nullglob
        mv ${{ github.workspace }}/october/* ${{ github.workspace }}
        rmdir ${{ github.workspace }}/plugin/
        rmdir ${{ github.workspace }}/october/
        ln -ls ${{ github.workspace }}
        cat ${{ github.workspace }}/composer.json
