name: Setup October CMS
description: Installs October CMS and dependencies for testing plugins
inputs:
  plugin:
    description: "The plugin directory to store the current plugin repository within, eg: 'author/plugin'"
    required: true
  cmsVersion:
    description: The October CMS version to install
    required: true
    default: dev-develop as 1.1
  libraryVersion:
    description: The Rain Library version to install
    required: true
    default: dev-develop as 1.1
runs:
  using: composite
  steps:
    - name: Stage plugin
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/plugin/${{ inputs.plugin }}
        ls -A ${{ github.workspace }}
